<?php

namespace App\Exceptions;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Arr;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $exception)
    {

        if ($exception instanceof \Illuminate\Validation\ValidationException) {
            if (request()->wantsJson() || request()->ajax()) {
                $arr = array();
                $errors_data = [];
                $messages = $exception->errors();
                $mainMessage = null;
                foreach ($messages as $key => $row) {
                    $errors_data['fieldname'] = $key;
                    $errors_data['message'] = $row[0];
                    $arr[] = $errors_data;

                    if (!isset($mainMessage))
                        $mainMessage = $row[0];
                }
                return response()->json(['status' => false, 'statusCode' => 422, 'message' => $mainMessage, 'items' => $arr]);
            }

            return redirect()->back()->withErrors($exception->errors())->withInput(request()->all());
        }
        return parent::render($request, $exception); // TODO: Change the autogenerated stub
    }

    protected function unauthenticated($request, AuthenticationException $exception)
    {

        if ($request->expectsJson() || $request->segment(1) == 'api') {

            return response_api(false, 401, null, empObj());
        }

        $guard = Arr::get($exception->guards(), 0);

        switch ($guard) {
            case 'admin':
                $login = $guard . '/login';
                break;
            default:
                $login = 'login';
                break;
        }
        return redirect()->guest($login);
    }

}
